use serde::{Deserialize, Serialize};

/// Stable identifier for a single device (a phone, tablet, web tab, or future
/// server-side player). Generated client-side, persisted across launches,
/// reused on reconnect.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct DeviceId(pub String);

impl DeviceId {
    #[allow(dead_code)]
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }
}

impl std::fmt::Display for DeviceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DeviceKind {
    Ios,
    Android,
    Web,
    Server,
}

/// One item in the playback queue. `item_id` is generated by the player
/// and is stable for the item's lifetime; controllers use it to address
/// the item in `RemoveFromQueue` / `ReorderQueue` / `AddToQueue`. The
/// server never reuses or mints these — they're player-owned.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct QueueItem {
    pub item_id: String,
    pub track_id: i32,
}

/// Snapshot of playback published by the active player. Player-authoritative:
/// the player decides what's true; maki relays it. Cached on the server so
/// late-joining controllers and handoff have something to read.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlaybackState {
    /// Identifier of the currently-playing queue item, or `None` if idle.
    /// The track_id for the current item is found by matching this against
    /// `queue`. Players generate these; controllers address by them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_item_id: Option<String>,
    pub position_ms: i64,
    pub is_playing: bool,
    pub queue: Vec<QueueItem>,
    /// Unix millis of when this snapshot was taken on the player.
    pub updated_at: i64,
}

/// Commands a controller sends; maki routes to the active player's WS.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Command {
    Play,
    Pause,
    Toggle,
    Next,
    Previous,
    Seek {
        position_ms: i64,
    },
    SetQueue {
        track_ids: Vec<i32>,
        start_index: i32,
    },
    AddToQueue {
        track_id: i32,
        /// Insert after the item with this id. `None` appends to the end.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        after_item_id: Option<String>,
    },
    RemoveFromQueue {
        item_id: String,
    },
    ReorderQueue {
        item_id: String,
        /// Move `item_id` to after the item with this id. `None` moves it
        /// to the start of the queue.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        after_item_id: Option<String>,
    },
}

/// First message a device sends on connect. The server uses the device_id
/// to dedupe reconnecting devices.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Identify {
    pub device_id: DeviceId,
    pub name: String,
    pub kind: DeviceKind,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    Identify(Identify),
    PublishState { state: PlaybackState },
    Command { command: Command },
    Transfer { to_device_id: DeviceId },
    Heartbeat,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeviceInfo {
    pub device_id: DeviceId,
    pub name: String,
    pub kind: DeviceKind,
    pub is_active_player: bool,
    /// Unix millis of last incoming message from this device.
    pub last_seen: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    /// Sent right after IDENTIFY, so the client can render the room.
    Welcome {
        your_device_id: DeviceId,
        active_device_id: Option<DeviceId>,
        devices: Vec<DeviceInfo>,
        last_state: Option<PlaybackState>,
    },
    /// Broadcast to all OTHER devices of the user when the active player
    /// publishes. `seq` is monotonic per user-session.
    State {
        state: PlaybackState,
        from_device_id: DeviceId,
        seq: u64,
    },
    /// Presence change (device connected, disconnected, or active-player moved).
    DeviceList {
        devices: Vec<DeviceInfo>,
        active_device_id: Option<DeviceId>,
    },
    /// A routed command from a controller, delivered only to the active player.
    Command {
        command: Command,
        from_device_id: DeviceId,
    },
    /// Request to the active player to re-publish its state (e.g. after a
    /// transfer or stale cache).
    RequestPublish,
    Error {
        code: String,
        message: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    NoActivePlayer,
    NotActivePlayer,
    UnknownDevice,
    InvalidMessage,
    Internal,
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            ErrorCode::NoActivePlayer => "no_active_player",
            ErrorCode::NotActivePlayer => "not_active_player",
            ErrorCode::UnknownDevice => "unknown_device",
            ErrorCode::InvalidMessage => "invalid_message",
            ErrorCode::Internal => "internal",
        };
        f.write_str(s)
    }
}

impl ServerMessage {
    pub fn error(code: ErrorCode, message: impl Into<String>) -> Self {
        ServerMessage::Error {
            code: code.to_string(),
            message: message.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T: Serialize + serde::de::DeserializeOwned>(value: &T) -> T {
        let json = serde_json::to_string(value).unwrap();
        serde_json::from_str(&json).unwrap()
    }

    #[test]
    fn device_id_round_trips_as_string() {
        let id = DeviceId::new("abc-123");
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, "\"abc-123\"");
        let back: DeviceId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn device_kind_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&DeviceKind::Ios).unwrap(), "\"ios\"");
        assert_eq!(
            serde_json::to_string(&DeviceKind::Android).unwrap(),
            "\"android\""
        );
        assert_eq!(serde_json::to_string(&DeviceKind::Web).unwrap(), "\"web\"");
        assert_eq!(
            serde_json::to_string(&DeviceKind::Server).unwrap(),
            "\"server\""
        );
    }

    #[test]
    fn client_message_identify_round_trips() {
        let msg = ClientMessage::Identify(Identify {
            device_id: DeviceId::new("dev-1"),
            name: "Phone".into(),
            kind: DeviceKind::Ios,
        });
        let back: ClientMessage = round_trip(&msg);
        assert_eq!(back, msg);
        // wire format check
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"identify\""));
        assert!(json.contains("\"device_id\":\"dev-1\""));
        assert!(json.contains("\"kind\":\"ios\""));
    }

    #[test]
    fn client_message_publish_state_round_trips() {
        let msg = ClientMessage::PublishState {
            state: PlaybackState {
                current_item_id: Some("i-2".into()),
                position_ms: 12345,
                is_playing: true,
                queue: vec![
                    QueueItem {
                        item_id: "i-1".into(),
                        track_id: 1,
                    },
                    QueueItem {
                        item_id: "i-2".into(),
                        track_id: 42,
                    },
                    QueueItem {
                        item_id: "i-3".into(),
                        track_id: 3,
                    },
                ],
                updated_at: 1_700_000_000_000,
            },
        };
        let back: ClientMessage = round_trip(&msg);
        assert_eq!(back, msg);
    }

    #[test]
    fn command_set_queue_round_trips() {
        let cmd = Command::SetQueue {
            track_ids: vec![10, 20, 30],
            start_index: 1,
        };
        let back: Command = round_trip(&cmd);
        assert_eq!(back, cmd);
        // wire: tag is "kind"
        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("\"kind\":\"set_queue\""));
        assert!(json.contains("\"track_ids\":[10,20,30]"));
    }

    #[test]
    fn command_add_to_queue_after_omitted_when_none() {
        let cmd = Command::AddToQueue {
            track_id: 7,
            after_item_id: None,
        };
        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("\"track_id\":7"));
        assert!(!json.contains("after_item_id"));
        let back: Command = round_trip(&cmd);
        assert_eq!(back, cmd);
    }

    #[test]
    fn command_remove_from_queue_round_trips() {
        let cmd = Command::RemoveFromQueue {
            item_id: "i-3".into(),
        };
        let back: Command = round_trip(&cmd);
        assert_eq!(back, cmd);
        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("\"kind\":\"remove_from_queue\""));
        assert!(json.contains("\"item_id\":\"i-3\""));
    }

    #[test]
    fn command_reorder_queue_round_trips() {
        let cmd = Command::ReorderQueue {
            item_id: "i-2".into(),
            after_item_id: Some("i-5".into()),
        };
        let back: Command = round_trip(&cmd);
        assert_eq!(back, cmd);

        let cmd_start = Command::ReorderQueue {
            item_id: "i-2".into(),
            after_item_id: None,
        };
        let json = serde_json::to_string(&cmd_start).unwrap();
        assert!(!json.contains("after_item_id"));
        let back: Command = round_trip(&cmd_start);
        assert_eq!(back, cmd_start);
    }

    #[test]
    fn command_seek_round_trips() {
        let cmd = Command::Seek {
            position_ms: 99_999,
        };
        let back: Command = round_trip(&cmd);
        assert_eq!(back, cmd);
    }

    #[test]
    fn client_transfer_round_trips() {
        let msg = ClientMessage::Transfer {
            to_device_id: DeviceId::new("dev-2"),
        };
        let back: ClientMessage = round_trip(&msg);
        assert_eq!(back, msg);
    }

    #[test]
    fn server_welcome_round_trips() {
        let msg = ServerMessage::Welcome {
            your_device_id: DeviceId::new("dev-1"),
            active_device_id: Some(DeviceId::new("dev-2")),
            devices: vec![DeviceInfo {
                device_id: DeviceId::new("dev-1"),
                name: "Phone".into(),
                kind: DeviceKind::Ios,
                is_active_player: false,
                last_seen: 1,
            }],
            last_state: Some(PlaybackState {
                current_item_id: Some("i-1".into()),
                position_ms: 100,
                is_playing: true,
                queue: vec![QueueItem {
                    item_id: "i-1".into(),
                    track_id: 5,
                }],
                updated_at: 1,
            }),
        };
        let back: ServerMessage = round_trip(&msg);
        assert_eq!(back, msg);
    }

    #[test]
    fn server_state_seq_round_trips() {
        let msg = ServerMessage::State {
            state: PlaybackState {
                current_item_id: None,
                position_ms: 0,
                is_playing: false,
                queue: Vec::new(),
                updated_at: 0,
            },
            from_device_id: DeviceId::new("dev-1"),
            seq: 7,
        };
        let back: ServerMessage = round_trip(&msg);
        assert_eq!(back, msg);
    }

    #[test]
    fn server_error_helper() {
        let msg = ServerMessage::error(ErrorCode::NoActivePlayer, "no device");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"error\""));
        assert!(json.contains("\"code\":\"no_active_player\""));
        assert!(json.contains("\"message\":\"no device\""));
    }
}
