import type { Metadata } from "next";
import { Figtree, IBM_Plex_Mono } from "next/font/google";
import { SessionProvider } from "@/contexts/Session";
import "./globals.css";

const fig = Figtree({ subsets: ["latin"], variable: "--font-fig" });
const mono = IBM_Plex_Mono({ subsets: ["latin"], weight: "400", variable: "--font-mono" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${fig.className} ${mono.variable}`}>{children}</body>
      </SessionProvider>
    </html>
  );
}
